# Use root/example as user/password credentials
version: '3.1'

services:

  dbmy:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ihm
      MYSQL_USER: ihm
      MYSQL_ROOT_PASSWORD: ihm
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - db-ihm:/var/lib/mysql

volumes:
    db-ihm:
      driver: local
