<?php

namespace ContainerB7zumYZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LE1a3svService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LE1a3sv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LE1a3sv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'noteRepository' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService', true],
        ], [
            'noteRepository' => 'App\\Repository\\NoteRepository',
        ]);
    }
}
