<?php

namespace ContainerEBAE1wD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ikle3oqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ikle3oq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ikle3oq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\NoteController::delete' => ['privates', '.service_locator.JPQzG4U', 'get_ServiceLocator_JPQzG4UService', true],
            'App\\Controller\\NoteController::edit' => ['privates', '.service_locator.JPQzG4U', 'get_ServiceLocator_JPQzG4UService', true],
            'App\\Controller\\NoteController::index' => ['privates', '.service_locator.LE1a3sv', 'get_ServiceLocator_LE1a3svService', true],
            'App\\Controller\\NoteController::show' => ['privates', '.service_locator.JPQzG4U', 'get_ServiceLocator_JPQzG4UService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\NoteController:delete' => ['privates', '.service_locator.JPQzG4U', 'get_ServiceLocator_JPQzG4UService', true],
            'App\\Controller\\NoteController:edit' => ['privates', '.service_locator.JPQzG4U', 'get_ServiceLocator_JPQzG4UService', true],
            'App\\Controller\\NoteController:index' => ['privates', '.service_locator.LE1a3sv', 'get_ServiceLocator_LE1a3svService', true],
            'App\\Controller\\NoteController:show' => ['privates', '.service_locator.JPQzG4U', 'get_ServiceLocator_JPQzG4UService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\NoteController::delete' => '?',
            'App\\Controller\\NoteController::edit' => '?',
            'App\\Controller\\NoteController::index' => '?',
            'App\\Controller\\NoteController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\NoteController:delete' => '?',
            'App\\Controller\\NoteController:edit' => '?',
            'App\\Controller\\NoteController:index' => '?',
            'App\\Controller\\NoteController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
