<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7zumYZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7zumYZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7zumYZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7zumYZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB7zumYZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'B7zumYZ',
    'container.build_id' => '6c996a54',
    'container.build_time' => 1604336118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB7zumYZ');
